package com.gamebuster19901.license;

public enum CheckerPhase {
	UNINITIALIZED,
	INITIALIZING,
	INITIALIZED,
	FINDING_SETTINGS,
	VALIDATING_SETTINGS,
	GETTING_HEADERS,
	CHECKING_HEADERS,
	APPLYING_HEADERS,
	STRIPPING_HEADERS,
	FAILED,
	SUCCESS;
}
